// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/rianekacahya/go-kafka/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// EventInvoker is an autogenerated mock type for the EventInvoker type
type EventInvoker struct {
	mock.Mock
}

// OrderProducers provides a mock function with given fields: _a0, _a1
func (_m *EventInvoker) OrderProducers(_a0 context.Context, _a1 *entity.Orders) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Orders) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
